### PR TITLE
Fixed typos and grammar

### PR DESCRIPTION
**Pull request by Bernasss12**
I'm really enjoying this book so far (I'm currently only on chapter 4)
I noticed a few mistakes as I followed along and thought I'd at least try to make this better than it already is.
The things I fixed were mostly typos, incorrect grammar, missing commas and added structural wrapping in multiple occasions.

While I was getting the repository and starting the changes I opened it on IDEA which started pointing out way more stuff than I had initially noticed, so I edited the first file, in 3 steps to it will be easier to discard anything you might think is unnecessary. I'm fully open to rolling back stuff, especially since the "style" recommendation are just that, recommendation the IDE gave.

Anyways I'll start with `chapter-00.md` today but I should be able to pump these out fairly quick whenever I have the time.

### CODE REVIEW

**Comment by lwjglgamedev** [comment]
Thanks! Please go on and complete the pull request. You cand maybe do it in an incremental way.

**Comment by Bernasss12** [comment]
I'm still in chapter 5 (since I'm trying all kinds of cursed things with kotlin and my time is pretty limited) so maybe I'll complete those for now and complete the pull request and then I'll do it as I finish reading each chapter.

**Comment by lwjglgamedev** [comment]
I was wondering if you could just complete this pull request as it is, since the changes are worth it.

**Comment by Bernasss12** [comment]
You're right! Sorry I left this hanging, might as well push everything I have so far (not much more xD)

**Comment by lwjglgamedev** [comment]
I was reviewing the pull request but I cannot understand the changes that you refer to strcuturla wrapping. Some of them make sense, but some others split too much the paragraphs. Can you explain the rationale behind them?

**Comment by Bernasss12** [comment]
> I was reviewing the pull request but I cannot understand the changes that you refer to strcuturla wrapping. Some of them make sense, but some others split too much the paragraphs. Can you explain the rationale behind them?

I don't really understand it fully, it's automatic in IDEA and it shouldn't change the final page.
It should basically just add `\n` to every line that goes over a certain length to allow it to be readable without horizontal scrolling. When the markdown is parsed `\n` are ignored so I'd say the point is just to improve readability of the raw file.

Then again I committed it separately so it could be easily dropped if it's not necessary so let me know :)

**Comment by lwjglgamedev** [comment]
Ok, understood, I will merge everything and maybe later on fix some line breaks (they should not be needed).

**Pull request merged**
