### PR TITLE
Major Structural & Written Changes

### PR DESCRIPTION
**Pull request by SWinxy**
This is a pr that is ongoing. I will continue to progress through this book, making changes I deem fit and making the newer chapters conform to the changes I've made in previous chapters. I've been sitting on this for like a week lol sorry, I couldn't figure out how I wanted to go through with this.

Major notes:
- `Render.java`'s init function is now the constructor.
- Many arrays are now ArrayLists
- Inlined return methods so that it can straight up return without needing to assign a temporary `null` variable (minorly faster; cleaner code).
- Removed check for the physical device name (rather unnecessary).
- Putting the extension for the Vulkan instance (in `Instance.java`) is put after the `VkInstanceCreateInfo` for a bit of a cleaner look.
- `Window.java` doesn't implement `GLFWFramebufferSizeCallbackI.java` now. Because you're already using a lambda for the callback, it's not even used.

Minor notes:
- Made a lot of fields `final`.
- Renamed `ByteBuffers` and `PointerBuffers` object names to match the parameters in LWJGL methods (ie `PointerBuffer pp = stack.mallocPointer(1)` to `PointerBuffer pDevice = stack.mallocPointer(1)`).
- Replaced one or two variables with the proper LWJGL buffer, rather than an array.
- Removed cases of `this.` preceding variables that really didn't need it.
- Some fields are condensed to one line where it makes sense (ie `int width, height;`).

Feel free to take a look, but a lot of it is quite uninteresting. __This pr is not done yet__. I'm getting other chapters done and I'd rather you know I'm working on this than one of us get frustrated spending time working on something that wasn't necessary.

### CODE REVIEW

**Comment by lwjglgamedev** [comment]
Thanks for this huge effort !

I will have a look to the changes, although what you propose seems logical to me, and will improve the quality of the code. For the code, I use IntelliJ autoformat while saving, I hope it does not undo the changes. I also user Sonarqube to analyze the code, I will check if there are any conflicts.

Just a quick question, to make sure I've understood everything. Do you plan to apply the changes to the rest of the chapters? I'm planning next chapters which maybe cascade shadow maps or skeletal animation (maybe calculating the joint matrices in a compute shader).

**Comment by SWinxy** [comment]
I do plan to do the rest of the chapters. I don't want you to be stuck doing menial changes, but rather continue making more chapters and I'll catch up eventually. I don't know what Intellij would do for the auto formatting, but all it does is switch some lines of code around (afaik).

**Comment by lwjglgamedev** [comment]
Ok, 

Thank you very the work. So I will keep on working on my branch, and I will merge the PR when it is complete. I have reviewed most of the changes and I tend to agree on most of them (There are some style differencies, for example, I tend ti use a single return in the functions, however your changes reduces the lines of code, improving readibiluty). The only changes that are not clear to me are:
- It seems to me that you removed the debug callback in the physical device (passed as an extension). Can you explain why? Although eventually, validation errors will be printed, it is the only way to control that output.
- I prefer not to remove the physical device selection by name. I think it is a usefule featuyre when you have several GPUs and want to make sure which one you are using.

On the other hand, I do not want to forget to add a special section with people who have contributed. Since you are one oof the most prolific ones, I was wondering how do you want to appear there. Just SWIinxy? Another name?

**Comment by SWinxy** [comment]
Are you talking about [here](https://github.com/lwjglgamedev/vulkanbook/pull/10/files#diff-21f71ba253213eeaeeec65641b009430a380eef1005d4ee5bed7ab8ac408265cL80-L85)? If not, I really don't know what you're talking about. This change I linked was just a style preference. No need to put anything in if the address is `NULL`.

You could put the GPU name selection back in. I couldn't find any stats on how many people have multiple GPUs, but I am pretty sure very few people have them, and the support for them is waning.

Just put me as SWinxy, thanks :)

**Comment by lwjglgamedev** [comment]
Ok, my bad. Yes it is only a style change, the code is still there. Please go on.

The thing with GPUs, is that if you hava a discrete GPU (Nvidia, AMD), you will end up  having two Vulkan GPUs, the one for that  GPU and the one provided by the CPU (in my case, Intel), if the the CPU is not very old. So I think it is a common case.

**Comment by SWinxy** [comment]
Y'know I never considered integrated GPUs, but yeah probably should avoid choosing them over a dedicated one ha.

**Comment by SWinxy** [comment]
Excuse my prolonged absence. I'm currently working on a Vulkan product that is expected to ship within a few weeks. When I have time (probably during Christmas), I will add a new way to do transparency, if you are okay with that.

**Comment by lwjglgamedev** [comment]
No problem. Please go ahead with transparencies. On the other hand, I was thinking about the changes in this pending pull request. Maybe you could split this PR into smaller changes, handling on topic at a time, but coovreing the whole set of chapters. Maybe that way it is easier to inbtegrate and to progress.

**Comment by SWinxy** [comment]
Yeah absolutely. Makes sense to go and do the cascading changes all at once, rather than coupling them with new changes.

**Comment by SWinxy** [comment]
Hey, I've had some issues with git and because of that I'm just going to delete this PR and start over. imo it's for the best.

**Comment by lwjglgamedev** [comment]
Thanks, please if you can split the changes in some categories. In case we have different views about one specific topic, it may help to integrate the other ones.

**Comment by SWinxy** [comment]
Yeah. The first PR will be minor, uncontroversial cleanup, such as [using IntBuffers instead of arrays](https://github.com/SWinxy/vulkanbook/commit/217cab23ff6e907467e53cf33e98bb2715a333bd), or organizing the fields in a consistent way. Learned to not bite off more than I can chew from this.

**Comment by lwjglgamedev** [comment]
Great, keep in mind (regarding fields arrangment), That I use IntelliJ auto formatter and basically try to order them alphabetically .

**Comment by SWinxy** [comment]
AFAIK the formatter will automatically detect separate chunks of fields, and sort them without screwing up your ordering. I've tested the `Code > Format File` options (in my code and in this project) and it will transform the fields in terms of state modifiers (eg `static`, `final`), and if it sees that you've separated them with a space, it won't delete the space.

**Pull request closed without merging**
