### PR TITLE
Copy check for chapters 00 to 02

### PR DESCRIPTION
**Pull request by SWinxy**
Rewrote some sentences, fixed typos, removed all the `this.` when it wasn't neeced, reworked the Window callbacks to conform with MouseInput, and imported things statically.

### CODE REVIEW

**Comment by lwjglgamedev** [comment]
Thanks for the work ! Please keep in mind that this is a way in progress (be benevolent  :D), however it is clear that your suggestions cleary improve the writing style. Thanks for that. 
Concerning the source code, I intented to use `this` to emphasize access to class attributes, however you made me think if I was going too verbose, I will probably follow your suggestions. There are some other changes that I need to think. For example, the Vulkan version. Why you go back to version 1.0?

Kind regards.

**Comment by SWinxy** [comment]
You are using the `VK10` class, which is version 1.0. If you want to use 1.1, go ahead and replace `VK10` with `VK11`. LWJGL doesn't have bindings for 1.2 yet.
image

**Comment by lwjglgamedev** [comment]
Yes, I'm aware of that, I was waiting for the next LWJGL release to use the
VK12. Maybe I will change all the references to VK11 and use 1.1 by now.

Best regards.

**Comment by SWinxy** [comment]
How do you want to go forward on this PR? If we change the code, we'd have to go through the rest of the chapters to make it conform.

**Comment by lwjglgamedev** [comment]
If you agree,

I will merge your PR and made the modifications later on the rest of the
chapters source code to be coherent.

Thanks for your contributions.

**Comment by SWinxy** [comment]
Go ahead.

**Comment by lwjglgamedev** [comment]
Updated the rest of the chapters. Some comments:
- If restored part of the source code for the Window class. I'm interested in being notified while the window resizes. Also, added a getKeyPressed method and an optional parameter for keys callback. I've changed also the description for that.
- Remove the use of  unnecesary `this`. 
- Changed thw way source code is included, contextualzing allways in the affected class.
- The ordre of som attributes have changed. (I let Intellij to autoformat on save and reorder attributes and methods).

I hope that I've not removed code from your pull request (with exceptions mentioned above). If you detect something, please come back to me.

Many thanks again for your contributions.

**Pull request merged**
